branches:
  only:
    - master

environment:
  nodejs_version: "8"
  GH_TOKEN:
    secure: mCHkUQ+tL4GmNF0UTbEtl5KsM+ZNX/qm5Fy3aAzkQScrkqhcf7w9Toz0bCT/EyWD

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-Product node $env:nodejs_version
  - md jsontmp
  - cd jsontmp
  - npm init -y
  - npm i json
  - cd ..
  - .\jsontmp\node_modules\.bin\json -I -f package.json -e "delete this.devDependencies.nopam; delete this.devDependencies.ocamlBetterErrors"
  - rm package-lock.json
  - npm i -g bs-platform
  - npm install

build_script:
  - npm run windows-build-all
  - npm run dist

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
