version: 2
jobs:
    build:
        working_directory: ~/spotify-to-youtube
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - restore-cache:
                key: node_modules
            - run: npm i bs-platform
            - run: npm install
            - run: npm test
            - save-cache:
                key: node_modules
                paths:
                    - node_modules
            #sudo apt-get update
            #sudo apt-get install xfce4 xfce4-goodies tightvncserver
            #USER=circleci vncserver
            #sudo apt-get install libxss1 lsof
            #sudo apt-get install gconf2
            #sudo apt-get install libnss3
            #cd spotify-to-youtube/
            #DISPLAY=:1.0 electron lib/js/src/main.js