version: 2
jobs:
    build:
        working_directory: ~/spotify-to-youtube
        docker:
            - image: circleci/node
        steps:
            - checkout
            - restore-cache:
              key: node_modules
            - run: npm install
            - run: npm test
            - save-cache:
                key: node_modules
                paths:
                    - node_modules