version: 2
jobs:
    build:
        working_directory: ~/spotify-to-youtube
        docker:
            - image: circleci/node:7
            - image: consol/ubuntu-xfce-vnc
                command: vncserver
        steps:
            - checkout
            - restore-cache:
                key: node_modules
            - run: npm install
            - run: DEBUG=electron-rebuild ./node_modules/.bin/electron-rebuild
            - run: npm test
            - save-cache:
                key: node_modules
                paths:
                    - node_modules