version: 2
jobs:
    build:
        working_directory: ~/spotify-to-youtube
        docker:
            - image: circleci/node:7
        steps:
            - run: printf "password\npassword" > vncpw
            - run: vncpasswd < vncpw
            - run: rm vncpw
            - run: vnc4server -geometry 1280x1024 -depth 24
            - checkout
            - restore-cache:
                key: node_modules
            - run: npm install
            - run: DEBUG=electron-rebuild ./node_modules/.bin/electron-rebuild
            - run: npm test
            - save-cache:
                key: node_modules
                paths:
                    - node_modules